POST http://localhost:8080/signUp
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "login": "aina",
  "password": "aina"
}

###

POST http://localhost:8080/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "login": "aina",
  "password": "aina"
}

###

GET http://localhost:8080/api/application?id=1

###

GET http://localhost:8080/api/application?gitUrl="dsad"

###

GET http://localhost:8080/api/application?ownerName="aina"

###

POST http://localhost:8080/api/application
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "gitUrl": "a12312",
  "ownerName": "aina"
}

###



