### Create an account, register

POST http://localhost:8080/signUp
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "login": "aina",
  "password": "aina"
}

### Authenticate, get token

POST http://localhost:8080/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "login": "aina",
  "password": "aina"
}

### Show all applications

GET http://localhost:8080/applications
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.tNUVLtXwKaH5x1whga7TQbuOpCEDAl3_T_V4v6Jm_9CAQBJc4X_GsEXzgU3BWwGOe2A8g81ji9XuvXreEMaEaQ

### Create an application

POST http://localhost:8080/applications
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.tNUVLtXwKaH5x1whga7TQbuOpCEDAl3_T_V4v6Jm_9CAQBJc4X_GsEXzgU3BWwGOe2A8g81ji9XuvXreEMaEaQ

{
  "gitUrl": "https://github.com/Dimanaux/java-lab-iaas-2020.git"
}

### Get application's data

GET http://localhost:8080/applications/1
Accept: */*
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.tNUVLtXwKaH5x1whga7TQbuOpCEDAl3_T_V4v6Jm_9CAQBJc4X_GsEXzgU3BWwGOe2A8g81ji9XuvXreEMaEaQ

### NOT SUPPORTED YET

PUT http://localhost:8080/applications/1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.tNUVLtXwKaH5x1whga7TQbuOpCEDAl3_T_V4v6Jm_9CAQBJc4X_GsEXzgU3BWwGOe2A8g81ji9XuvXreEMaEaQ

{
  "_comment": "NOT SUPPORTED YET"
}

### Destroy application

DELETE http://localhost:8080/applications/1
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.tNUVLtXwKaH5x1whga7TQbuOpCEDAl3_T_V4v6Jm_9CAQBJc4X_GsEXzgU3BWwGOe2A8g81ji9XuvXreEMaEaQ

### Get free ports

GET http://localhost:8080/api/ports
Accept: application/json

### Check port
GET http://localhost:8080/api/port/1109
Accept: application/json

###

