POST http://localhost:8080/signUp
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "login": "aina",
  "password": "aina"
}

###

POST http://localhost:8080/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "login": "aina",
  "password": "aina"
}

###

GET http://localhost:8080/api/application/id?id=1

###

GET http://localhost:8080/api/application/gitUrl?gitUrl=dsad

###

GET http://localhost:8080/api/application/userName?userName=aina
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJsb2dpbiI6ImFpbmEiLCJpZCI6MX0.tNUVLtXwKaH5x1whga7TQbuOpCEDAl3_T_V4v6Jm_9CAQBJc4X_GsEXzgU3BWwGOe2A8g81ji9XuvXreEMaEaQ
###

POST http://localhost:8080/api/application
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "gitUrl": "a12312",
  "ownerName": "aina"
}

###



